export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const ERROR = "ERROR";

// TEST GET DATA
export const GET_USERS = "GET_USERS";
export const DELETE_USERS = "DELETE_USERS";
export const EDIT_USERS = "EDIT_USERS";
export const USERS_ERROR = "USERS_ERROR";

export const GET_ADMIN = "GET_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const EDIT_ADMIN = "EDIT_ADMIN";
export const ADMIN_ERROR = "ADMIN_ERROR";

export const GET_CMSUSERS = "GET_CMSUSERS";
export const DELETE_CMSUSERS = "DELETE_CMSUSERS";
export const EDIT_CMSUSERS = "EDIT_CMSUSERS";
export const CMSUSERS_ERROR = "CMSUSERS_ERROR";

export const GET_VIDEOEDUKASI = "GET_VIDEOEDUKASI";
export const DELETE_VIDEOEDUKASI = "DELETE_VIDEOEDUKASI";
export const EDIT_VIDEOEDUKASI = "EDIT_VIDEOEDUKASI";
export const ERROR_VIDEOEDUKASI = "ERROR_VIDEOEDUKASI";

export const GET_ARTIKELMINGGUAN = "GET_ARTIKELMINGGUAN";
export const DELETE_ARTIKELMINGGUAN = "DELETE_ARTIKELMINGGUAN";
export const EDIT_ARTIKELMINGGUAN = "EDIT_ARTIKELMINGGUAN";
export const ERROR_ARTIKELMINGGUAN = "ERROR_ARTIKELMINGGUAN";
